sonar.projectKey=ui5-typescript-helloworld
sonar.host.url=http://localhost:9000
sonar.sources=webapp/
sonar.exclusions=webapp/localService/**/*,webapp/test/**/*
sonar.javascript.lcov.reportPath=coverage/lcov.info
sonar.token=sqp_f3d9d75cbdd3057e2a459bcd00f7f895c17306b0